In [1]:
### Parte A:

In [2]:
#Importamos paquetes
import pandas as pd
import os
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from scipy.stats import ttest_ind
from sklearn.model_selection import train_test_split

In [3]:
# Del tp anterior, importamos la base construida para lo pedido en ella.

In [4]:
os.chdir(r"C:\Users\Gaelj\OneDrive\Documentos\GitHub\E337_Grupo2\TP3")

In [5]:
ocupados1 = pd.read_csv("ocupados.csv")

In [6]:
ocupados2 = pd.read_csv("ocupados2.csv")

C:\Users\Gaelj\AppData\Local\Temp\ipykernel_16664\1476564008.py:1: DtypeWarning: Columns (0,12,102,105) have mixed types. Specify dtype option on import or set low_memory=False.
  ocupados2 = pd.read_csv("ocupados2.csv")

In [7]:
ocupados3 = pd.read_csv("ocupados3.csv")

C:\Users\Gaelj\AppData\Local\Temp\ipykernel_16664\2394547012.py:1: DtypeWarning: Columns (0,12,102,105) have mixed types. Specify dtype option on import or set low_memory=False.
  ocupados3 = pd.read_csv("ocupados3.csv")

In [8]:
ocupados1.columns

Index(['CH04', 'CH06', 'CH07', 'CH08', 'NIVEL_ED', 'ESTADO', 'CAT_INAC',
       'IPCF', 'CH14', 'CH15_COD', 'CH16_COD', 'PP03C', 'PP04B_COD', 'PP06H',
       'PP07A', 'AÑO', 'CAT_OCUP', 'PP07H', 'informal', 'EMPLEO', 'edad2',
       'CH12', 'CH13', 'educ', 'ingreso_total_familiar', 'horastrab',
       'ix_tot'],
      dtype='object')

In [9]:
ocupados2.columns

Index(['CODUSU', 'ANO4', 'TRIMESTRE', 'NRO_HOGAR', 'COMPONENTE', 'H15',
       'REGION', 'MAS_500', 'AGLOMERADO', 'PONDERA',
       ...
       'V21_M', 'PJ1_1', 'PJ2_1', 'PJ3_1', 'IDIMPP', 'ingreso_total_familiar',
       'ingreso_total_familiar_mill', 'informal', 'horastrab', 'ix_tot'],
      dtype='object', length=249)

In [10]:
ocupados3.columns

Index(['CODUSU', 'ANO4', 'TRIMESTRE', 'NRO_HOGAR', 'COMPONENTE', 'H15',
       'REGION', 'MAS_500', 'AGLOMERADO', 'PONDERA',
       ...
       'AÑO', 'V2_M', 'V5_M', 'V11_M', 'V21_M', 'PJ1_1', 'PJ2_1', 'PJ3_1',
       'IDIMPP', 'informal'],
      dtype='object', length=245)

In [11]:
# Nosotros utilizamos varias bases para trabajar en disintas cosas, por lo que importamos todas para indentificar bien cuál sería la correcta a usar
# Viendo esto, usemos la base de ocupados2 que parece la más completa, pero agregemos la variable de edad y edad al cuadrado que no la tiene

In [12]:
ocupados = ocupados2.copy()

In [13]:
ocupados["edad2"] = ocupados["CH06"]**2

In [14]:
# Agregamos lo contruido en ocupados1 que es la variable educ que nos va a servir para más adelante

In [15]:
ocupados['educ'] = ocupados1['educ']

In [16]:
ocupados

,CODUSU,ANO4,TRIMESTRE,NRO_HOGAR,COMPONENTE,H15,REGION,MAS_500,AGLOMERADO,PONDERA,...,PJ2_1,PJ3_1,IDIMPP,ingreso_total_familiar,ingreso_total_familiar_mill,informal,horastrab,ix_tot,edad2,educ
0,TQRMNOTYPHKOKQCDEHNHB00867020,2025.0,3.0,1.0,8.0,0.0,42.0,S,27.0,528.0,...,NaN,NaN,NaN,1252000.0,1.25200,NaN,NaN,9,81.0,NaN
1,TQRMNOTYPHKOKQCDEHNHB00867020,2025.0,3.0,1.0,9.0,0.0,42.0,S,27.0,528.0,...,NaN,NaN,NaN,1252000.0,1.25200,NaN,NaN,9,4.0,17.0
2,TQRMNOTYPHKOKQCDEHNHB00867020,2025.0,3.0,1.0,1.0,1.0,42.0,S,27.0,528.0,...,NaN,NaN,NaN,1252000.0,1.25200,NaN,0.0,9,1444.0,17.0
3,TQRMNOTYPHKOKQCDEHNHB00867020,2025.0,3.0,1.0,2.0,1.0,42.0,S,27.0,528.0,...,NaN,NaN,NaN,1252000.0,1.25200,0.0,NaN,9,1521.0,NaN
4,TQRMNOTYPHKOKQCDEHNHB00867020,2025.0,3.0,1.0,3.0,1.0,42.0,S,27.0,528.0,...,NaN,NaN,NaN,1252000.0,1.25200,NaN,NaN,9,324.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9259,287829,2005.0,3.0,1.0,2.0,1.0,42.0,N,27.0,227.0,...,0.0,0.0,0.0,711780.0,0.71178,1.0,NaN,6,529.0,NaN
9260,287829,2005.0,3.0,1.0,3.0,0.0,42.0,N,27.0,227.0,...,0.0,0.0,0.0,711780.0,0.71178,NaN,NaN,6,49.0,NaN
9261,287829,2005.0,3.0,1.0,4.0,0.0,42.0,N,27.0,227.0,...,0.0,0.0,0.0,711780.0,0.71178,NaN,NaN,6,25.0,NaN
9262,287829,2005.0,3.0,1.0,5.0,0.0,42.0,N,27.0,227.0,...,0.0,0.0,0.0,711780.0,0.71178,NaN,NaN,6,4.0,NaN
9263,287829,2005.0,3.0,1.0,6.0,1.0,42.0,N,27.0,227.0,...,0.0,0.0,0.0,711780.0,0.71178,NaN,NaN,6,5329.0,NaN

In [17]:
### 1)

In [18]:
ocupados_2005 = ocupados[ocupados['AÑO'] == 2005]
ocupados_2025 = ocupados[ocupados['AÑO'] == 2025]

In [19]:
### 2)

In [20]:
# Variables predictoras
variables_x = [
    'CH06',
    'edad2',
    'educ',
    'ingreso_total_familiar',
    'horastrab',
    'ix_tot'
]

# Lista para resultados
resultados = []

for var in variables_x:
    x2005 = ocupados_2005[var].dropna()
    x2025 = ocupados_2025[var].dropna()

    media_2005 = x2005.mean()
    media_2025 = x2025.mean()
    diferencia = media_2025 - media_2005

    t_stat, p_value = ttest_ind(x2025, x2005, equal_var=False)

    resultados.append({
        'Variable': var,
        'Media 2005': media_2005,
        'Media 2025': media_2025,
        'Diferencia': diferencia,
        'p-value': p_value
    })

tabla_medias = pd.DataFrame(resultados)
tabla_medias

C:\Users\Gaelj\anaconda3\Lib\site-packages\scipy\_lib\deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)

,Variable,Media 2005,Media 2025,Diferencia,p-value
0,CH06,3.130269e+01,3.663681e+01,5.334116,6.488601e-31
1,edad2,1.462081e+03,1.837150e+03,375.069465,1.247540e-23
2,educ,NaN,1.188013e+01,NaN,NaN
3,ingreso_total_familiar,1.250504e+06,1.245069e+06,-5435.344359,8.313485e-01
4,horastrab,2.996461e+01,2.412725e+01,-5.837360,4.925278e-10
5,ix_tot,4.702110e+00,3.884968e+00,-0.817142,7.886202e-86

In [21]:
# 3)

In [22]:
# Hagamos primero para la base de 2025

In [23]:
# La variable y va a estar definida por la variable que creamos en el tp anterior llamada "informal"
# El resto forma parte de las variables dependientes, es decir edad2, educ, ingreso_total_familiar, horastrab y ix_tot
# Construyamos primero eso entonces

In [24]:
# Guardemos primero las variables X relevantes solo para 2025

var_x = [
    'edad2',
    'educ',
    'ingreso_total_familiar',
    'horastrab',
    'ix_tot'
]

# Filtrar solamente las observaciones de 2025
ocupados_2025 = ocupados[ocupados['AÑO'] == 2025].copy()

# Crear la matriz X con solo esas variables
X_2025 = ocupados_2025[var_x].copy()

In [25]:
# Lo mismo vamos a hacer para 2005

# Filtrar solamente las observaciones de 2025
ocupados_2005 = ocupados[ocupados['AÑO'] == 2005].copy()

# Crear la matriz X con solo esas variables
X_2005 = ocupados_2005[var_x].copy()

In [26]:
X_2025

       edad2  educ  ingreso_total_familiar  horastrab  ix_tot
0       81.0   NaN               1252000.0        NaN       9
1        4.0  17.0               1252000.0        NaN       9
2     1444.0  17.0               1252000.0        0.0       9
3     1521.0   NaN               1252000.0        NaN       9
4      324.0   NaN               1252000.0        NaN       9
...      ...   ...                     ...        ...     ...
4472  1521.0   NaN               1260000.0        NaN       4
4473   361.0   NaN               1260000.0        NaN       4
4474   256.0   NaN               1260000.0        NaN       4
4475   625.0   NaN                200000.0        0.0       2
4476    36.0   NaN                200000.0        NaN       2

[4477 rows x 5 columns]

In [27]:
X_2005

       edad2  educ  ingreso_total_familiar  horastrab  ix_tot
4477  2601.0   NaN               2372600.0       60.0       4
4478  2500.0   NaN               2372600.0        NaN       4
4479   529.0   NaN               2372600.0        NaN       4
4480   361.0   NaN               2372600.0        NaN       4
4481  1225.0   NaN                332164.0       46.0       4
...      ...   ...                     ...        ...     ...
9259   529.0   NaN                711780.0        NaN       6
9260    49.0   NaN                711780.0        NaN       6
9261    25.0   NaN                711780.0        NaN       6
9262     4.0   NaN                711780.0        NaN       6
9263  5329.0   NaN                711780.0        NaN       6

[4787 rows x 5 columns]

In [28]:
# Ahora, guardemos también por separado la variable dependiente y:

y_2025 = ocupados_2025['informal'].copy()
y_2005= ocupados_2005['informal'].copy()

In [29]:
print(X_2025.shape)
print(y_2025.shape)

print(X_2005.shape)
print(y_2005.shape)

(4477, 5)
(4477,)
(4787, 5)
(4787,)

In [30]:
# Con esto, deberíamos poder divir las muestras entre train y test con la función dada

In [31]:
X2025_train, X2025_test, y2025_train, y2025_test = train_test_split(X_2025, y_2025, test_size=0.70, random_state=444)

In [32]:
X2005_train, X2005_test, y2005_train, y2005_test = train_test_split(X_2005, y_2005, test_size=0.70, random_state=444)

In [33]:
# Me estaría faltando agregar la constante nada más

In [34]:
X2025_train['constante'] = 1

X2025_test['constante'] = 1

y2025_train['constante'] = 1

y2025_test['constante'] = 1

In [35]:
X2005_train['constante'] = 1

X2005_test['constante'] = 1

y2005_train['constante'] = 1

y2005_test['constante'] = 1

In [36]:
### Parte b