In [1]:
#Importamos paquetes
import pandas as pd
import os
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
os.chdir(r"C:\Users\Gaelj\OneDrive\Documentos\Universidad San Andres\4° Año\Big Data\Cosas Poster")

In [3]:
### Encuesta México Victimización

In [4]:
# Abramos primero las bases que tenemos

In [5]:
df_mexvict_hogar = pd.read_csv(r"C:\Users\Gaelj\OneDrive\Documentos\Universidad San Andres\4° Año\Big Data\Cosas Poster\Encuesta México Victimización\THogar.csv")

In [6]:
df_mexvict_hogar # Características de los hogares que componen la vivienda seleccionada.

,Unnamed: 0,ID_VIV,ID_HOG,UPM,VIV_SEL,HOGAR,RESUL_H,N_INF,R_SEL,CVE_ENT,NOM_ENT,CVE_MUN,NOM_MUN,TOT_PER,FAC_HOG,FAC_HOG_AM,DOMINIO,EST_DIS,UPM_DIS
0,1,100107.01,0100107.01.01,100107,1,1,B,1.0,1.0,1,AGUASCALIENTES,1,AGUASCALIENTES,1.0,241.0,241.0,U,1,47
1,2,100107.02,0100107.02.01,100107,2,1,A,1.0,2.0,1,AGUASCALIENTES,1,AGUASCALIENTES,4.0,241.0,241.0,U,1,47
2,3,100107.03,0100107.03.01,100107,3,1,B,1.0,4.0,1,AGUASCALIENTES,1,AGUASCALIENTES,4.0,241.0,241.0,U,1,47
3,4,100107.04,0100107.04.01,100107,4,1,A,2.0,3.0,1,AGUASCALIENTES,1,AGUASCALIENTES,4.0,241.0,241.0,U,1,47
4,5,100107.05,0100107.05.01,100107,5,1,B,1.0,1.0,1,AGUASCALIENTES,1,AGUASCALIENTES,4.0,241.0,241.0,U,1,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91325,91326,3261231.16,3261231.16.01,3261231,16,1,B,1.0,1.0,32,ZACATECAS,51,VILLA DE COS,1.0,282.0,NaN,R,746,13744
91326,91327,3261231.17,3261231.17.01,3261231,17,1,B,1.0,1.0,32,ZACATECAS,51,VILLA DE COS,4.0,282.0,NaN,R,746,13744
91327,91328,3261231.18,3261231.18.01,3261231,18,1,B,1.0,1.0,32,ZACATECAS,51,VILLA DE COS,1.0,282.0,NaN,R,746,13744
91328,91329,3261231.19,3261231.19.01,3261231,19,1,B,2.0,2.0,32,ZACATECAS,51,VILLA DE COS,4.0,282.0,NaN,R,746,13744
91329,91330,3261231.20,3261231.20.01,3261231,20,1,A,1.0,1.0,32,ZACATECAS,51,VILLA DE COS,2.0,282.0,NaN,R,746,13744

In [7]:
df_Mod_Vic = pd.read_csv(r"C:\Users\Gaelj\OneDrive\Documentos\Universidad San Andres\4° Año\Big Data\Cosas Poster\Encuesta México Victimización\TMod_Vic.csv")

In [8]:
df_Mod_Vic #Características correspondientes a los delitos captados por el módulo sobre victimización.

,Unnamed: 0,ID_VIV,ID_HOG,ID_PER,ID_DEL,UPM,VIV_SEL,HOGAR,ND_TIPO,TD_TIPO,...,BP6_1,BP6_2,BP6_3,BP7_1,FAC_DEL,FAC_DEL_AM,DOMINIO,ESTRATO,EST_DIS,UPM_DIS
0,1,100271.01,0100271.01.01,0100271.01.01.02,0100271.01.01.02.05.1,100271,1,1,1,2,...,NaN,NaN,NaN,NaN,606,606.0,U,1,1,87
1,2,100149.02,0100149.02.01,0100149.02.01.04,0100149.02.01.04.02.1,100149,2,1,1,1,...,NaN,NaN,NaN,NaN,242,242.0,U,2,1,46
2,3,102068.05,0102068.05.01,0102068.05.01.01,0102068.05.01.01.05.1,102068,5,1,1,1,...,NaN,NaN,NaN,NaN,279,279.0,U,2,1,6
3,4,100255.05,0100255.05.01,0100255.05.01.02,0100255.05.01.02.02.1,100255,5,1,1,1,...,NaN,NaN,NaN,NaN,198,198.0,U,3,2,174
4,5,100461.05,0100461.05.01,0100461.05.01.01,0100461.05.01.01.04.1,100461,5,1,1,2,...,NaN,NaN,NaN,NaN,255,255.0,U,4,3,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40275,40276,1900792.01,1900792.01.01,1900792.01.01.01,1900792.01.01.01.07.1,1900792,1,1,1,1,...,NaN,NaN,NaN,NaN,770,NaN,U,4,410,8392
40276,40277,3017025.03,3017025.03.01,3017025.03.01.01,3017025.03.01.01.07.1,3017025,3,1,1,1,...,NaN,NaN,NaN,NaN,1331,NaN,U,2,701,12966
40277,40278,2203439.13,2203439.13.01,2203439.13.01.01,2203439.13.01.01.07.3,2203439,13,1,3,3,...,NaN,NaN,NaN,NaN,1436,NaN,C,4,499,9692
40278,40279,2804521.03,2804521.03.01,2804521.03.01.02,2804521.03.01.02.15.1,2804521,3,1,1,1,...,NaN,NaN,NaN,NaN,505,NaN,U,3,627,12164
40279,40280,2203439.13,2203439.13.01,2203439.13.01.01,2203439.13.01.01.07.1,2203439,13,1,1,3,...,NaN,NaN,NaN,NaN,1436,NaN,C,4,499,9692

In [9]:
df_TPer_Vic1 = pd.read_csv(r"C:\Users\Gaelj\OneDrive\Documentos\Universidad San Andres\4° Año\Big Data\Cosas Poster\Encuesta México Victimización\TPer_Vic1.csv")

In [10]:
df_TPer_Vic1 #Variables correspondientes a la percepción de seguridad pública y el desempeño institucional.

,Unnamed: 0,ID_VIV,ID_HOG,ID_PER,UPM,VIV_SEL,HOGAR,RESUL_H,R_SEL,SEXO,...,AP5_8_11_5,AP5_9,FAC_HOG,FAC_ELE,FAC_HOG_AM,FAC_ELE_AM,DOMINIO,ESTRATO,EST_DIS,UPM_DIS
0,1,100107.01,0100107.01.01,0100107.01.01.01,100107,1,1,B,1,2,...,NaN,3,241,241,241.0,241.0,U,2,1,47
1,2,100107.02,0100107.02.01,0100107.02.01.02,100107,2,1,A,2,2,...,9.0,2,241,482,241.0,482.0,U,2,1,47
2,3,100107.03,0100107.03.01,0100107.03.01.04,100107,3,1,B,4,2,...,NaN,9,241,963,241.0,963.0,U,2,1,47
3,4,100107.04,0100107.04.01,0100107.04.01.03,100107,4,1,A,3,1,...,9.0,2,241,723,241.0,723.0,U,2,1,47
4,5,100107.05,0100107.05.01,0100107.05.01.01,100107,5,1,B,1,2,...,NaN,2,241,482,241.0,482.0,U,2,1,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91177,91178,3261231.16,3261231.16.01,3261231.16.01.01,3261231,16,1,B,1,1,...,NaN,3,282,282,NaN,NaN,R,2,746,13744
91178,91179,3261231.17,3261231.17.01,3261231.17.01.01,3261231,17,1,B,1,2,...,NaN,2,282,282,NaN,NaN,R,2,746,13744
91179,91180,3261231.18,3261231.18.01,3261231.18.01.01,3261231,18,1,B,1,2,...,NaN,9,282,282,NaN,NaN,R,2,746,13744
91180,91181,3261231.19,3261231.19.01,3261231.19.01.02,3261231,19,1,B,2,2,...,NaN,2,282,564,NaN,NaN,R,2,746,13744
91181,91182,3261231.20,3261231.20.01,3261231.20.01.01,3261231,20,1,A,1,1,...,NaN,4,282,564,NaN,NaN,R,2,746,13744

In [11]:
df_TPer_Vic2 = pd.read_csv(r"C:\Users\Gaelj\OneDrive\Documentos\Universidad San Andres\4° Año\Big Data\Cosas Poster\Encuesta México Victimización\TPer_Vic2.csv")

In [12]:
df_TPer_Vic2 #Características correspondientes a la victimización en el hogar y personal.

,Unnamed: 0,ID_VIV,ID_HOG,ID_PER,UPM,VIV_SEL,HOGAR,RESUL_H,R_SEL,SEXO,...,AP7_3_15,AP7_4_15,FAC_HOG,FAC_ELE,FAC_HOG_AM,FAC_ELE_AM,DOMINIO,ESTRATO,EST_DIS,UPM_DIS
0,1,100107.01,0100107.01.01,0100107.01.01.01,100107,1,1,B,1,2,...,2,NaN,241,241,241.0,241.0,U,2,1,47
1,2,100107.02,0100107.02.01,0100107.02.01.02,100107,2,1,A,2,2,...,2,NaN,241,482,241.0,482.0,U,2,1,47
2,3,100107.03,0100107.03.01,0100107.03.01.04,100107,3,1,B,4,2,...,2,NaN,241,963,241.0,963.0,U,2,1,47
3,4,100107.04,0100107.04.01,0100107.04.01.03,100107,4,1,A,3,1,...,2,NaN,241,723,241.0,723.0,U,2,1,47
4,5,100107.05,0100107.05.01,0100107.05.01.01,100107,5,1,B,1,2,...,2,NaN,241,482,241.0,482.0,U,2,1,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91177,91178,3261231.16,3261231.16.01,3261231.16.01.01,3261231,16,1,B,1,1,...,2,NaN,282,282,NaN,NaN,R,2,746,13744
91178,91179,3261231.17,3261231.17.01,3261231.17.01.01,3261231,17,1,B,1,2,...,2,NaN,282,282,NaN,NaN,R,2,746,13744
91179,91180,3261231.18,3261231.18.01,3261231.18.01.01,3261231,18,1,B,1,2,...,2,NaN,282,282,NaN,NaN,R,2,746,13744
91180,91181,3261231.19,3261231.19.01,3261231.19.01.02,3261231,19,1,B,2,2,...,2,NaN,282,564,NaN,NaN,R,2,746,13744
91181,91182,3261231.20,3261231.20.01,3261231.20.01.01,3261231,20,1,A,1,1,...,2,NaN,282,564,NaN,NaN,R,2,746,13744

In [13]:
df_TSDem = pd.read_csv(r"C:\Users\Gaelj\OneDrive\Documentos\Universidad San Andres\4° Año\Big Data\Cosas Poster\Encuesta México Victimización\TSDem.csv")

In [14]:
df_TSDem #Características sociodemográficas correspondientes a los integrantes del hogar

,Unnamed: 0,ID_VIV,ID_HOG,ID_PER,UPM,VIV_SEL,HOGAR,RESUL_H,CVE_ENT,NOM_ENT,...,NIV,GRA,AP3_8,AP3_9,AP3_10,FAC_HOG,FAC_HOG_AM,DOMINIO,EST_DIS,UPM_DIS
0,1,100107.01,0100107.01.01,0100107.01.01.01,100107,1,1,B,1,AGUASCALIENTES,...,3.0,2.0,1.0,NaN,2.0,241,241.0,U,1,47
1,2,100107.02,0100107.02.01,0100107.02.01.01,100107,2,1,A,1,AGUASCALIENTES,...,6.0,3.0,1.0,NaN,2.0,241,241.0,U,1,47
2,3,100107.02,0100107.02.01,0100107.02.01.02,100107,2,1,A,1,AGUASCALIENTES,...,6.0,3.0,1.0,NaN,2.0,241,241.0,U,1,47
3,4,100107.02,0100107.02.01,0100107.02.01.03,100107,2,1,A,1,AGUASCALIENTES,...,2.0,4.0,NaN,NaN,NaN,241,241.0,U,1,47
4,5,100107.02,0100107.02.01,0100107.02.01.04,100107,2,1,A,1,AGUASCALIENTES,...,1.0,3.0,NaN,NaN,NaN,241,241.0,U,1,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300649,300650,3261231.19,3261231.19.01,3261231.19.01.02,3261231,19,1,B,32,ZACATECAS,...,3.0,3.0,1.0,NaN,1.0,282,NaN,R,746,13744
300650,300651,3261231.19,3261231.19.01,3261231.19.01.03,3261231,19,1,B,32,ZACATECAS,...,3.0,3.0,NaN,NaN,NaN,282,NaN,R,746,13744
300651,300652,3261231.19,3261231.19.01,3261231.19.01.04,3261231,19,1,B,32,ZACATECAS,...,2.0,1.0,NaN,NaN,NaN,282,NaN,R,746,13744
300652,300653,3261231.20,3261231.20.01,3261231.20.01.01,3261231,20,1,A,32,ZACATECAS,...,3.0,3.0,1.0,NaN,1.0,282,NaN,R,746,13744
300653,300654,3261231.20,3261231.20.01,3261231.20.01.02,3261231,20,1,A,32,ZACATECAS,...,2.0,5.0,1.0,NaN,1.0,282,NaN,R,746,13744

In [15]:
df_TVivienda = pd.read_csv(r"C:\Users\Gaelj\OneDrive\Documentos\Universidad San Andres\4° Año\Big Data\Cosas Poster\Encuesta México Victimización\TVivienda.csv")

In [16]:
df_TVivienda # Características de las viviendas seleccionadas, sus integrantes y los hogares que las conforman.

,Unnamed: 0,ID_VIV,UPM,VIV_SEL,AREAM,CVE_ENT,NOM_ENT,CVE_MUN,NOM_MUN,RESULT_V,...,AP1_2,AP2_1,AP2_2,AP2_3,NAP2_3,FAC_VIV,FAC_VIV_AM,DOMINIO,EST_DIS,UPM_DIS
0,1,100107.01,100107,1,14.0,1,AGUASCALIENTES,1,AGUASCALIENTES,2,...,2,1,1,NaN,1,241,241.0,U,1,47
1,2,100107.02,100107,2,14.0,1,AGUASCALIENTES,1,AGUASCALIENTES,1,...,2,4,1,NaN,1,241,241.0,U,1,47
2,3,100107.03,100107,3,14.0,1,AGUASCALIENTES,1,AGUASCALIENTES,2,...,2,4,1,NaN,1,241,241.0,U,1,47
3,4,100107.04,100107,4,14.0,1,AGUASCALIENTES,1,AGUASCALIENTES,1,...,1,4,1,NaN,1,241,241.0,U,1,47
4,5,100107.05,100107,5,14.0,1,AGUASCALIENTES,1,AGUASCALIENTES,2,...,2,4,1,NaN,1,241,241.0,U,1,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89662,89663,3261231.16,3261231,16,NaN,32,ZACATECAS,51,VILLA DE COS,2,...,2,1,1,NaN,1,282,NaN,R,746,13744
89663,89664,3261231.17,3261231,17,NaN,32,ZACATECAS,51,VILLA DE COS,2,...,2,4,1,NaN,1,282,NaN,R,746,13744
89664,89665,3261231.18,3261231,18,NaN,32,ZACATECAS,51,VILLA DE COS,2,...,2,1,1,NaN,1,282,NaN,R,746,13744
89665,89666,3261231.19,3261231,19,NaN,32,ZACATECAS,51,VILLA DE COS,2,...,2,4,1,NaN,1,282,NaN,R,746,13744
89666,89667,3261231.20,3261231,20,NaN,32,ZACATECAS,51,VILLA DE COS,1,...,2,2,1,NaN,1,282,NaN,R,746,13744

In [ ]:
#NOM_MUN aparenta ser los municipios que se tienen en la base. Y NOM_ENT seria el nombre de la entidad 

#Por lo que es obvio, si me intereza mirar la persepción sobre la seguridad tendría que ver df_TPer_Vic1

#Antes que nada me gustaría definir que preguntas nos podríamos hacer con esto

In [ ]:
# Preguntas:

# 1) ¿Cómo varía la percepción de inseguridad según sexo y edad?
# 2) ¿La confianza en las instituciones está asociada a la percepción de inseguridad?
# 3) ¿Las víctimas cambian más sus hábitos por miedo al delito?

In [ ]:
# Empecemos entonces buscar una forma de ver la priemra pregunta

In [ ]:
# Para poder ver esto, vamos a neceditar distintas bases, siendo estas df_TSDem y df_TPer_Vic1
# Antes de eso, estaria bueno guardar todo dentro de regiones en vez de tener todos los estados por separado.

In [20]:
df_TSDem['NOM_ENT']

0         AGUASCALIENTES
1         AGUASCALIENTES
2         AGUASCALIENTES
3         AGUASCALIENTES
4         AGUASCALIENTES
               ...
300649         ZACATECAS
300650         ZACATECAS
300651         ZACATECAS
300652         ZACATECAS
300653         ZACATECAS
Name: NOM_ENT, Length: 300654, dtype: object

In [23]:
# Paso 1: estandarizar nombres
df_TSDem["NOM_ENT"] = df_TSDem["NOM_ENT"].str.strip().str.upper()
df_TPer_Vic1["NOM_ENT"] = df_TPer_Vic1["NOM_ENT"].str.strip().str.upper()

# Paso 2: diccionario corregido (adaptado a ENVIPE)
regiones_mexico = {
    "Noroeste": [
        "BAJA CALIFORNIA", "BAJA CALIFORNIA SUR", "CHIHUAHUA",
        "DURANGO", "SINALOA", "SONORA"
    ],
    "Noreste": [
        "COAHUILA DE ZARAGOZA", "NUEVO LEON", "TAMAULIPAS"
    ],
    "Occidente": [
        "COLIMA", "GUANAJUATO", "JALISCO",
        "MICHOACAN DE OCAMPO", "NAYARIT"
    ],
    "Centronorte": [
        "AGUASCALIENTES", "QUERETARO",
        "SAN LUIS POTOSI", "ZACATECAS"
    ],
    "Centrosur": [
        "CIUDAD DE MEXICO", "MEXICO", "MORELOS"
    ],
    "Oriente": [
        "HIDALGO", "PUEBLA", "TLAXCALA",
        "VERACRUZ DE IGNACIO DE LA LLAVE"
    ],
    "Suroeste": [
        "CHIAPAS", "GUERRERO", "OAXACA"
    ],
    "Sureste": [
        "CAMPECHE", "QUINTANA ROO",
        "TABASCO", "YUCATAN"
    ]
}

In [24]:
# Paso 3: función
def asignar_region(estado):
    for region, estados in regiones_mexico.items():
        if estado in estados:
            return region
    return "No clasificado"

# Paso 4: aplicar
df_TSDem["region"] = df_TSDem["NOM_ENT"].apply(asignar_region)
df_TPer_Vic1["region"] = df_TPer_Vic1["NOM_ENT"].apply(asignar_region)

In [25]:
print(df_TSDem["region"].value_counts())

region
Noroeste       54345
Occidente      43575
Oriente        41316
Sureste        36773
Centrosur      35038
Suroeste       32311
Noreste        30357
Centronorte    26939
Name: count, dtype: int64

In [26]:
df_TSDem[df_TSDem["region"] == "No clasificado"]["NOM_ENT"].drop_duplicates()

Series([], Name: NOM_ENT, dtype: object)

In [27]:
# Ahora hacemo merge para todo esto 

df_analisis = df_TPer_Vic1.merge(
    df_TSDem[["UPM", "VIV_SEL", "HOGAR", "N_REN", "SEXO", "EDAD", "region"]],
    left_on=["UPM", "VIV_SEL", "HOGAR", "R_SEL"],
    right_on=["UPM", "VIV_SEL", "HOGAR", "N_REN"],
    how="inner"
)

In [30]:
print(df_analisis.columns)

Index(['Unnamed: 0', 'ID_VIV', 'ID_HOG', 'ID_PER', 'UPM', 'VIV_SEL', 'HOGAR',
       'RESUL_H', 'R_SEL', 'SEXO_x',
       ...
       'FAC_ELE_AM', 'DOMINIO', 'ESTRATO', 'EST_DIS', 'UPM_DIS', 'region_x',
       'N_REN', 'SEXO_y', 'EDAD_y', 'region_y'],
      dtype='object', length=246)

In [31]:
df_analisis[["SEXO_y", "EDAD_y", "region_y"]].head()

   SEXO_y  EDAD_y     region_y
0       2      56  Centronorte
1       2      30  Centronorte
2       2      18  Centronorte
3       1      22  Centronorte
4       2      36  Centronorte